### ISSUE TITLE
Explicit exporting for named expressions and inline partials

### ISSUE THREAD

**Issue by tbateson** [horseshoe/horseshoe#19]
Currently when templates are imported using `{{> MyTemplate.U }}` all named expressions and inline partials are exported. This can be potentially troublesome if `MyTemplate.U` includes another template or there is private data that shouldn't be exported, resulting in inadvertent scope pollution. I propose that values be considered private unless explicitly exported. Additionally, values imported from another template are not exported by default (of course you can still explicitly export these values). I'm imagining something like this:

```
{{ myPrivateVar -> [1,2,3] }}
{{ myExportedVar -> [1: 2, 3: 4] }}
{{ myPrivateFunc(a) -> a + 1 }}
{{ myExportedExpr(b) -> b + 1 }}
{{<- myExportedVar, myExportedExpr }}{{! exported to any including file }}
{{< MyInlinePartial }}
Hello world!{{/}}
{{<- MyInlinePartial }}{{! additional invocations append }}
{{> AnotherFileThatExportsMyOtherValue.U }}
{{<- myOtherValue }}{{! imported from another template but forwarded }}
```

And then from the including side:

```
{{> MyTemplate }}{{! includes all exported symbols }}
{{ myExportedVar() }}
```
OR
```
{{> MyTemplate myExportedVar, myOtherValue }}{{! only imports the specified symbols }}
{{ myExportedVar() }}
```

**Comment by nicklauslittle** [comment]
What if we did something like `{{ export myExportedVar -> [1: 2, 3: 4] }}`?

**Comment by tbateson** [comment]
Given that keywords have been shied away from until now, it seems out of place. What about `{{<< myExportedVar -> [1: 2, 3: 4] }}` ?

I do like the idea of combining it with the declaration so that you don't need a separate line to export.

**Comment by nicklauslittle** [comment]
Yeah, I'm not a big fan of using export in general now that I think about it. I'm thinking it may be a better idea to explicitly import named expressions into the current template as in your second example. It probably wouldn't be any more annoying than exporting and you wouldn't have to worry about pollution from unwanted expressions, like in this example:
```horseshoe
{{! template1.U }}
{{! intValue() below pollutes the template by overriding the java.lang.Double method in template2 }}
{{ intValue() -> [1, 2, 3, 4, 5] }}
{{ myDoubles() -> [1.0, 2.0, 3.14159, 4.0, 5.0] }}

{{! template2.U }}
{{> template1.U }}
{{# myDoubles() }}
	{{# 'The real value is ' + . }}{{ intValue() }}) {{ . }}{{/}}
{{/}}
```

I'm trying to figure out some sort of unambiguous syntax for loading partials (`{{> }}`). Spaces are probably not a good idea since they can be in filenames. I'm not sure there is an unambiguous way without introducing another tag. Maybe it's just better to have a really uncommon character? Maybe `<`, `>`, `|`? (These characters aren't allowed in Windows filenames, but pretty much everything is allowed in *nix.) Thoughts?

**Comment by nicklauslittle** [comment]
Maybe we can do `{{> template.U | myVar, myFunc() }}`, but still allow `{{> template.U | * }}` to import everything? And `{{> template.U }}` would import nothing, just use the template for content?

**Comment by nicklauslittle** [comment]
I've implemented #21 as in my previous post (using `|` as the separator between partial and imports). I'm considering using `>` instead of `|`. Any preference?

**Comment by tbateson** [comment]
I like `|` as the separator. I'm looking at #21 and it looks like it only applies to named expressions, do you plan to include inline partials as well?

**Comment by nicklauslittle** [comment]
Inline partials are not currently included when a partial is included. Are you suggesting we do that as part of this issue? (If so, we may have to impose some naming restrictions on partials. Otherwise, it's hard to disambiguate the syntax.)

**Comment by tbateson** [comment]
I was under the assumption that inline partials would be included. Although since this isn't the case, it should be brought up in a separate issue.
