### ISSUE TITLE
Remove functionality for inline partials and section partials when closing tag is encountered

### ISSUE THREAD

**Issue by nicklauslittle** [horseshoe/horseshoe#6]
Currently, the `{{/}}` tag is always considered stand-alone for trailing white-space/newlines when closing an inline partial or a section partial. What if we introduced a new tag (`{{//}}`) that has these properties when closing any section?

**Comment by tbateson** [comment]
So currently
```mustache
{{# [1, 2] }}
{{.}}
{{/}}
```
results in `1\n2\n`? And
```mustache
{{# [1, 2] }}
{{.}}
{{//}}
```
would result in `1\n2`?

Also, why do inline partials operate like this currently?

**Comment by nicklauslittle** [comment]
No. It has to do with inline partials.
```horseshoe
{{< p }}
Hello
{{/}}
{{> p }} Bob!
```
results in `Hello\n Bob!`. The only way to make it into a single line is to do either
```horseshoe
{{< p }}
Hello{{/}}
{{> p }} Bob!
```
or
```horseshoe
{{< p }}Hello{{/}}
{{> p }} Bob!
```
. Both of these should insert a new line into the content when parsing the inline partial (`\nHello Bob!`) because the `{{/}}` tag doesn't qualify for stand-aloneness. I added custom code in the section partials branch that ignores newlines after the closing tag for inline partials to allow these examples to work "correctly" (no newline when parsing inline partial). This proposal is to introduce `{{//}}` which always ignores trailing white-space and newline, and to remove the custom code for inline partial closing tags.

**Comment by nicklauslittle** [comment]
The more I think about this, the more I'm more inclined to not change this. Some of the reasons include:
1) `//` conflicts with comments in expressions.
2) It's confusing having multiple representations of closing tags, and people are likely going to forget to use it where they need it.
