### ISSUE TITLE
New instance support

### ISSUE THREAD

**Issue by tbateson** [horseshoe/horseshoe#62]
In order to create new instances within a template, you need to do something like this (below doesn't actually work, is only examplary):

```
{{ ~@'ClassName'.getConstructor([~@'ParamType1', ~@'ParamType2', ..., ~@'ParamTypeN'].toArray(~@'java.lang.reflect.Array'.newInstance(~@'java.lang.Class', N))).newInstance([Arg1, Arg2, ..., ArgN].toArray()) }}
```

I propose the following syntax for non-language-specific instance creation:
```
{{ ~@'ClassName'{ Arg1, Arg2, ..., ArgN } }}
```
For example, `{{ file := ~@'java.io.File'{ "Test.txt" } }}` would invoke the first `File` single argument constructor.

In the case of ambiguous arguments, the form `~@'ClassName'< ParamType1, ParamType2, ..., ParamTypeN >{ Arg1, Arg2, ..., ArgN }` could be used instead. `~@'java.io.File'< java.lang.String >{ "Test.txt" }` would explicitly invoke the `File` `String` constructor.

**Comment by nicklauslittle** [comment]
What if we just did something like `~@'java.io.File'.new('Test.txt')`? It could reuse a lot of the existing syntax for methods, instead of coming up with an entirely new syntax (pun intended). This would make it easier to implement. We also don't have to worry about trailing curly braces and the tag-close syntax (`}}`).

**Comment by tbateson** [comment]
That is an acceptable solution. If we do take that approach, it should be formalized in the README how to disambiguate between same-argument-count methods, as right now there is no description of the feature.

**Comment by nicklauslittle** [comment]
My plan is to eventually have a better algorithm for resolving methods / constructors, so there might be less of a need to disambiguate them in the future. But currently the way to do this is to use backticks to quote the method name (which is `new` for constructors), a colon, and a comma-separated list of parameter type names (simple name or canonical name) up to the number of parameters of the method: For example, ``~@Math.`min:int`(...)`` is sufficient to identify `Math.min(int, int)`.

Do you have any recommendations on changes, or does it seem good as is?
