### ISSUE TITLE
Implement list slices

### ISSUE THREAD

**Issue by tbateson** [horseshoe/horseshoe#8]
# Slices as array subscript extension
```
{{ ls = [1, 2, 3]; ls2 = ls[1:2]; ls2 }}
```
returns `[2, 3]`
Another use case:
```
{{ ls = [3, 4, 5]; ls2 = [1, 2] + ls[:1]; ls2 }}
```
returns `[1, 2, 3, 4]`
It would also be useful (but not entirely necessary) to have a spread operator (`[1, 2, ...[3, 4]] == [1, 2, 3, 4]`), but since lists are additive this isn't completely necessary.

This would add the following array subscript forms: `List[m:]`, `List[m:n]`, and `List[:n]`.

**Comment by nicklauslittle** [comment]
Why not just
```horseshoe
{{ [1, 2, 3].subList(1, 3) }}
```
?

**Comment by nicklauslittle** [comment]
I added `List[m:n]` in #12. `List[:n]` would be `List[0:n]`. `List[m:]` would be `List[m:-1]` (or any negative number).

**Comment by tbateson** [comment]
I'm not a fan of `[m:-n]` (`[0:n]` is very obvious since `[:n]` is syntactical sugar), but I can envision a scenario where a programming error slips by because of this.

**Comment by nicklauslittle** [comment]
Yeah, I wasn't a big fan either. Unfortunately, implementing `[m:]` would require a significant change in how some of the code works. We could just leave it out, but I'm not really a big fan of that either.

**Comment by nicklauslittle** [comment]
Although, technically, it is pretty easy to get the same functionality without special syntax: `List[m:]` -> `List[m:List.size() - 1]`.

**Comment by nicklauslittle** [comment]
A lot of the Java functions slice using an exclusive end index. (`List[m:n+1]`) The only benefit I see with this is that it allows getting 0 length lists using `List[n:n]`. Thoughts?
