### ISSUE TITLE
Documentative else section tags

### ISSUE THREAD

**Issue by tbateson** [horseshoe/horseshoe#81]
Currently there is no way to expressively declare what section start tag an else section is in reference to. I propose the following section tag to do so: `{{^^ <tag> }}`. This section tag would work similarly to the `{{/ <tag> }}` in that it would require the content of the section tag to be equal to the starting section tag.

Examples:
```
{{# IsTrue() }}
blahblahblah
{{^^ IsTrue() }} {{! Performs no calculation, like closing '/' tags }}
foobar 
{{/ IsTrue() }}
```

```
{{# IsTrue() }}
blahblahblah
{{^^ IsFalse() }} {{! <-- Error, must be equal to the starting section tag }}
abcde
{{/ IsTrue() }}
```

```
{{^^ IsFalse() }} {{! <-- Error, must be preceded by a {{# starting section tag }}
blah
{{/ IsFalse() }}
```

**Comment by nicklauslittle** [comment]
Sounds good to me. If you have any suggestions on how to document else-if tags (and end-if tags with nested else-if tags) I would be interested to hear those as well.
